trigger:
- main

pool:
  name: 'Default'



variables:
  buildConfiguration: 'Release'
  webAppName: 'Kalkulator20992'

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node.js'

- script: |
    npm ci
    npm run build
  displayName: 'Build frontend (Sass + minify)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
  displayName: 'Use .NET SDK'

- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet build'

- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish
  displayName: 'dotnet publish'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'SC-kalkulator-nowy'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/publish'
